export const USER_REQUEST_FETCHING = 'USER_REQUEST_FETCHING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE';

export const LANDS_REQUEST_FETCHING = 'LANDS_REQUEST_FETCHING';
export const LANDS_REQUEST_SUCCESS = 'LANDS_REQUEST_SUCCESS';
export const LANDS_REQUEST_FAILURE = 'LANDS_REQUEST_FAILURE';

export const ADD_LAND_FETCHING = 'ADD_LAND_FETCHING';
export const ADD_LAND_SUCCESS = 'ADD_LAND_SUCCESS';
export const ADD_LAND_FAILURE = 'ADD_LAND_FAILURE';
export const DELETE_LAND_SUCCESS = 'DELETE_LAND_SUCCESS';
